### ISSUE TITLE
这个不支持多环境呢！！！dev test prod

### ISSUE THREAD

**Issue by moyuanhui** [zengqinglei/Creekdream.Configuration.Apollo#1]

**Comment by zengqinglei** [comment]
这个可以通过如下图：
![image](https://user-images.githubusercontent.com/7374317/49158723-c8bae600-f35d-11e8-9485-5bf760c6b496.png)
根据不同环境的appsettings.json 去覆盖 Apollo meta地址来对应不同环境。

你看看是否可行？

**Comment by moyuanhui** [comment]
还是不好，我已经修改源码了，调整客户端代码

**Comment by zengqinglei** [comment]
@moyuanhui 是否可以公布一下你的源码，互相学习和参考，谢谢！
